### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1055

### ISSUE THREAD

**Issue by Kryp3ton** [khzg/littlelink-admin#15]
`SQLSTATE[42000]: Syntax error or access violation: 1055 'littlelink.users.littlelink_name' isn't in GROUP BY (SQL: select 'users'.'littlelink_name', max(links.created_at) as created_at from 'links' inner join 'users' on 'users'.'id' = 'links'.'user_id' group by 'links'.'user_id' order by 'created_at' desc limit 4)`

How i resolve this error? plss help

**Comment by khzg** [comment]
sorry, This project will no longer be updated, use its new fork.

https://github.com/LinkStackOrg/LinkStack
